// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2Tnzgd93gViVZ-XxPEvAJ95FNUEjjEc',
    appId: '1:93936072854:web:001f41c648225c9eaaaab7',
    messagingSenderId: '93936072854',
    projectId: 'bulu-flutter-chat-7fb7e',
    authDomain: 'bulu-flutter-chat-7fb7e.firebaseapp.com',
    storageBucket: 'bulu-flutter-chat-7fb7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYIOXsidPpP7YsrvK6gvffVKGtVCcjhU',
    appId: '1:93936072854:android:14f9796b3013d450aaaab7',
    messagingSenderId: '93936072854',
    projectId: 'bulu-flutter-chat-7fb7e',
    storageBucket: 'bulu-flutter-chat-7fb7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqh_j1kKe5JVIC4W4lpSOhyQUIgSYwmSc',
    appId: '1:93936072854:ios:e97e772669f3e895aaaab7',
    messagingSenderId: '93936072854',
    projectId: 'bulu-flutter-chat-7fb7e',
    storageBucket: 'bulu-flutter-chat-7fb7e.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqh_j1kKe5JVIC4W4lpSOhyQUIgSYwmSc',
    appId: '1:93936072854:ios:54e74595d62d9107aaaab7',
    messagingSenderId: '93936072854',
    projectId: 'bulu-flutter-chat-7fb7e',
    storageBucket: 'bulu-flutter-chat-7fb7e.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
